# Generated by Django 4.0.5 on 2023-02-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_password',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_password',
        ),
    ]
