# Generated by Django 4.1 on 2023-02-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photo'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_amount', models.CharField(max_length=100)),
                ('transaction_status', models.CharField(default='pending', max_length=100)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.buyer')),
                ('product_id', models.ManyToManyField(blank=True, null=True, to='db.product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.seller')),
            ],
        ),
    ]
