# Generated by Django 4.1.7 on 2023-02-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_buyer_buyer_photo_alter_product_product_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateField(auto_now=True),
        ),
    ]
