# Generated by Django 4.1 on 2023-02-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_transactions_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(default='Processing', max_length=100)),
                ('dispute', models.BooleanField(default=False)),
                ('dispute_reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('disputed_by', models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], default=None, max_length=100, null=True)),
                ('solved_dispute', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default=None, max_length=20, null=True)),
                ('wronged_party', models.CharField(blank=True, choices=[('buyer', 'buyer'), ('seller', 'seller')], default=None, max_length=20, null=True)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.transactions')),
            ],
        ),
    ]
