# Generated by Django 4.1.7 on 2023-02-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_city',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_pincode',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_state',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_pincode',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='seller_state',
        ),
    ]
