# Generated by Django 4.1.7 on 2023-02-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='product_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.product'),
        ),
    ]
