# Generated by Django 4.1.7 on 2023-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_transactions_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='created', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_status',
            field=models.CharField(choices=[('holding', 'holding'), ('refunded', 'refunded'), ('paid', 'paid')], default='holding', max_length=100),
        ),
    ]
