# Generated by Django 4.1 on 2023-02-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_order_status_order_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='seller_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_status',
        ),
        migrations.AddField(
            model_name='transactions',
            name='order_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='db.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
